### ISSUE TITLE
Getting Unsupported message digest Exception

### ISSUE THREAD

**Issue by msmukesh5** [Bedework/bw-calendar-client#1]
I downloaded the Bedework 3.10.2 quickstart and configured it in our system. 
While adding the users from the JMX-console  as mentioned in your documentation  https://wiki.jasig.org/display/BWK310/Authentication+and+user+accounts
i am facing an Unsupported message digest  Exception.
org.bedework.selfreg.common.exception.SelfregException: Unsupported message digest

Need HELP .

**Comment by douglm** [comment]
There's a config option - MessageDigest - which should be visible on that screen. Legal values are "SSHA", "SHA", or "MD5" (without quotes). SHA I think is the appropriate value.

Set the field, click on "Apply Changes" then invoke the "saveConfig" operation to save the settings to file.

Then retry the add user operation

**Comment by msmukesh5** [comment]
Thanks for the help But,
I tried implementing your answer same way as you said and now i am getting a new exception in the JMX-console while adding users

edu.rpi.cmt.db.hibernate.HibException: org.hibernate.HibernateException: Could not find datasource

Need HELP.

**Comment by msmukesh5** [comment]
I Got the solution,
We need to make use LDAP = true 
MessageDigest = MD5
Set the field, click on "Apply Changes" then invoke the "saveConfig" operation to save the settings to file.
then it will work.
